---
- name: Copy the Redis Exporter systemd service file
  template:
    src: redis_exporter.service.j2
    dest: /etc/systemd/system/redis_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart redis_exporter

- name: Allow Redis Exporter port in SELinux on Redhat OS family
  seport:
    parts: "{{ redis_exporter_web_listen_addres.split(':')[-1] }}"
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"
