---
- name: Install dependencies
  package:
    name: "{{ item }}"
    state: present
  register: _install_dep_package is success
  until: _install_dep_package is success
  retries: 5
  delay: 2
  with_items: "{{ redis_exporter_dependencies }}"

- name: Create the redis_exporter group
  group:
    name: "{{ redis_exporter_system_group }}"
    state: present
    system: true
  when: redis_exporter_system_group != "root"

- name: Create the redis_exporter user
  user:
    name: "{{ redis_exporter_system_user }}"
    groups: "{{ redis_exporter_system_group }}"
    append: true
    shell: /usr/bin/nologin
    system: true
    create_home: false
    home: /
  when: redis_exporter_system_user != "root"

- block:
    - name: Download redis_exporter binary to local folder
      become: false
      get_url:
        url: "https://github.com/oliver006/redis_exporter/releases/download/v{{ redis_exporter_version }}/redis_exporter-v{{ redis_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        dest: "/tmp/redis_exporter-v{{ redis_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        checksum: "sha256:{{ redis_exporter_checksum }}"
      register: _download_binary
      until: _download_binary is success
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false

    - name: Unpack redis_exporter binary
      become: false
      unarchive:
        src: "/tmp/redis_exporter-v{{ redis_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        dest: "/tmp"
        creates: "/tmp/redis_exporter-v{{ redis_exporter_version }}.linux-{{ go_arch }}/redis_exporter"
      delegate_to: localhost
      check_mode: false

    - name: Propagate redis_exporter binaries
      copy:
        src: "/tmp/redis_exporter-v{{ redis_exporter_version }}.linux-{{ go_arch }}/redis_exporter"
        dest: "/usr/local/bin/redis_exporter"
        mode: 0755
        owner: root
        group: root
      notify: restart redis_exporter
      when: not ansible_check_mode
  when: redis_exporter_binary_local_dir | length == 0

- name: propagate locally distributed redis_exporter binary
  copy:
    src: "{{ redis_exporter_binary_local_dir }}/redis_exporter"
    dest: "/usr/local/bin/redis_exporter"
    mode: 0755
    owner: root
    group: root
  when: redis_exporter_binary_local_dir | length > 0
  notify: restart redis_exporter
