---
- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_majar_version | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_majar_version | lower }}.yml"
    - "{{ ansible_distribution_file_variety | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - redis_exporter_install
    - redis_exporter_configure
    - redis_exporter_run

- import_tasks: preflight.yml
  tags:
    - redis_exporter_install
    - redis_exporter_configure
    - redis_exporter_run

- import_tasks: install.yml
  become: true
  when: (not __redis_exporter_is_installed.stat.exists) or (__redis_exporter_current_version_output.stderr_lined[0].split(" ")[2] != redis_exporter_version)
  tags:
    - redis_exporter_install

- import_tasks: configure.yml
  become: true
  tags:
    - redis_exporter_configure

- name: Ensure Redis Exporter is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: redis_exporter
    enabled: true
    state: started
  tags:
    - redis_exporter_run

